/*
 * EntraOps Reporting - Tenant Governance Snapshot core (shared)
 *
 * Parses window.ENTRAOPS_CONFIGANALYZER_DATA (generated by
 * New-EntraOpsTenantGovernanceConfigurationAnalyzerData) into the snapshot/blob model used
 * by every app that visualizes the Tenant Governance Snapshot: the Configuration Analyzer
 * itself (change timeline / compare), the Conditional Access Analysis app (CA policy flow +
 * coverage gaps), the EIDSCA Findings app and the Access Package Flow app.
 *
 * Deliberately NOT wrapped in an IIFE: every declaration here becomes a global (window.*),
 * so page-specific app.js files (each their own IIFE) can consume it after including this
 * script first. Loaded via a relative path from sibling app folders
 * (../ConfigurationAnalyzer/js/core.js) - see those apps' index.html.
 *
 * Dataset shape (window.ENTRAOPS_CONFIGANALYZER_DATA):
 *   { generatedAt, snapshotFolder, snapshots: [{ commitSha, commitDate, subject, hasDetail,
 *     workingTree?, resources: [{ p: "<type>/<category>/<name>.json", h: "<blobHash>" }] }],
 *     blobs: { "<blobHash>": <parsed resource JSON or null> } }
 */

var DATA = window.ENTRAOPS_CONFIGANALYZER_DATA || null;

// ---- Tiny DOM helpers ----------------------------------------------------------
function $(id) { return document.getElementById(id); }
function esc(s) {
    return String(s == null ? "" : s)
        .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
function fmtDate(iso) {
    var d = new Date(iso);
    if (isNaN(d)) return iso;
    return d.toISOString().slice(0, 10) + " " + d.toISOString().slice(11, 16) + " UTC";
}
function fmtDateShort(iso) {
    var d = new Date(iso);
    if (isNaN(d)) return iso ? String(iso) : "unknown date";
    return d.toISOString().slice(0, 10);
}
function truncate(s, n) {
    var text = String(s == null ? "" : s);
    return text.length > n ? text.slice(0, n - 1) + "…" : text;
}

if (DATA && typeof DATA.tenantName === "string" && DATA.tenantName.trim()) {
    var tenantNameEl = $("tenantName");
    if (tenantNameEl) tenantNameEl.textContent = DATA.tenantName.trim();
}

// A shared, non-dismissible health notice for every report that consumes the Configuration
// Analyzer dataset. Findings derived from a mixed snapshot must never look authoritative merely
// because the user navigated away from the Configuration Analyzer landing view.
function renderEntraOpsSnapshotHealth(containerId) {
    var health = DATA && DATA.snapshotHealth;
    if (!health) return;
    var stale = Array.isArray(health.staleResourceTypes) ? health.staleResourceTypes : [];
    if (health.isComplete !== false && !stale.length) return;
    var container = containerId
        ? document.getElementById(containerId)
        : (document.getElementById("caSnapshotHealth") || document.getElementById("entraopsSnapshotHealth"));
    if (!container) {
        container = document.getElementById("entraopsSnapshotHealth");
        if (!container) {
            container = document.createElement("div");
            container.id = "entraopsSnapshotHealth";
            var main = document.querySelector("main");
            if (!main) return;
            main.insertBefore(container, main.firstChild);
        }
    }
    if (!document.getElementById("entraopsSnapshotHealthStyles")) {
        var style = document.createElement("style");
        style.id = "entraopsSnapshotHealthStyles";
        style.textContent = ".entraops-snapshot-health{border:2px solid #c50f1f;border-left-width:8px;background:#fff4f4;color:#4f1115;padding:14px 16px;margin:0 0 18px;border-radius:8px}.entraops-snapshot-health strong{color:#a4262c}.entraops-snapshot-health ul{margin:8px 0 0 20px}.entraops-snapshot-health code{overflow-wrap:anywhere}";
        document.head.appendChild(style);
    }
    var states = Array.isArray(health.resourceTypeStates) ? health.resourceTypeStates : [];
    var staleStates = states.filter(function (item) { return item && item.status === "PreservedStale"; });
    var details = staleStates.map(function (item) {
        var source = item.publishedSnapshotId || item.publishedSource || "unknown source";
        return "<li><code>" + esc(item.resourceType) + "</code> — preserved from " + esc(source) + "</li>";
    }).join("");
    if (!details) {
        details = stale.map(function (resourceType) {
            return "<li><code>" + esc(resourceType) + "</code> — source snapshot unavailable</li>";
        }).join("");
    }
    details += states.filter(function (item) { return item && item.status === "PublishedWithErrors"; }).map(function (item) {
        var retained = Number(item.retainedResourceCount) || 0;
        return "<li><code>" + esc(item.resourceType) + "</code> — published with export errors" +
            (retained ? "; " + retained + " resource" + (retained === 1 ? "" : "s") + " retained from the previous snapshot" : "") + "</li>";
    }).join("");
    var diagnostics = Array.isArray(health.diagnostics) ? health.diagnostics : [];
    var diagnosticDetails = diagnostics.map(function (item) {
        var identity = [item.resourceType, item.errorCategory, item.errorCode].filter(Boolean).join(" / ");
        var occurrences = Number(item.occurrences) > 1 ? " (" + Number(item.occurrences) + " occurrences)" : "";
        return "<li><strong>" + esc(identity || "Capture error") + occurrences + ":</strong> " +
            esc(item.message || "No normalized message was returned.") +
            (item.remediationHint ? " <em>" + esc(item.remediationHint) + "</em>" : "") + "</li>";
    }).join("");
    var diagnosticText = health.errorDetailsUnavailable
        ? " Graph did not return parseable per-type diagnostics."
        : "";
    container.innerHTML = '<div class="entraops-snapshot-health" role="alert" aria-live="polite">' +
        '<strong>Partial Tenant Governance snapshot — findings may use stale configuration.</strong> ' +
        "Status: " + esc(health.status || "unknown") + ". " +
        (health.capturedDateTime ? "Attempt captured " + esc(fmtDate(health.capturedDateTime)) + ". " : "") +
        (stale.length ? stale.length + " stale resource type(s)." : "") + diagnosticText +
        (details ? "<ul>" + details + "</ul>" : "") +
        (diagnosticDetails ? "<details><summary>Capture diagnostics (" + diagnostics.length + ")</summary><ul>" + diagnosticDetails + "</ul></details>" : "") +
        "</div>";
}

if (document.readyState !== "loading") renderEntraOpsSnapshotHealth();
else document.addEventListener("DOMContentLoaded", function () { renderEntraOpsSnapshotHealth(); });

// ---- Snapshot / resource model ---------------------------------------------------
// Resource path: "<resourceType>/<category>/<name>.json" (see
// Save-EntraOpsTenantGovernanceSnapshotJson for the folder convention).
function parseResourcePath(p) {
    var segments = p.split("/");
    var file = segments[segments.length - 1].replace(/\.json$/i, "");
    return {
        type: segments[0] || "unknown",
        category: segments.slice(1, -1).join("/"),
        name: file
    };
}

var snapshots = [];
if (DATA && Array.isArray(DATA.snapshots)) {
    snapshots = DATA.snapshots.map(function (s) {
        var resources = (s.resources || []).map(function (r) {
            var meta = parseResourcePath(r.p);
            return { p: r.p, h: r.h, type: meta.type, category: meta.category, name: meta.name };
        });
        return {
            commitSha: s.commitSha,
            commitDate: s.commitDate,
            subject: s.subject,
            hasDetail: !!s.hasDetail,
            workingTree: !!s.workingTree,
            resources: resources
        };
    });
}

function blobContent(hash) {
    if (!DATA || !DATA.blobs) return undefined;
    return DATA.blobs[hash]; // undefined = not embedded, null = unparseable
}

function snapshotLabel(s, idx) {
    var label = fmtDateShort(s.commitDate) + " · " + (s.workingTree ? "(working tree)" : (s.commitSha ? String(s.commitSha).slice(0, 8) : "working"));
    return "#" + (idx + 1) + " " + label;
}

function allResourceTypes() {
    var set = {};
    snapshots.forEach(function (s) { s.resources.forEach(function (r) { set[r.type] = true; }); });
    return Object.keys(set).sort();
}

function detailedSnapshotIdxs() {
    var idxs = [];
    snapshots.forEach(function (s, i) { if (s.hasDetail) idxs.push(i); });
    return idxs;
}

// ---- Flatten + property diff -------------------------------------------------------
function isPrimitive(v) { return v === null || typeof v !== "object"; }

function flatten(value, prefix, out) {
    if (isPrimitive(value)) {
        out[prefix || "(value)"] = value === null ? "null" : String(value);
        return out;
    }
    if (Array.isArray(value)) {
        if (value.length === 0) { out[prefix] = "[]"; return out; }
        if (value.every(isPrimitive)) { out[prefix] = JSON.stringify(value); return out; }
        value.forEach(function (v, i) { flatten(v, prefix + "[" + i + "]", out); });
        return out;
    }
    var keys = Object.keys(value);
    if (keys.length === 0) { out[prefix] = "{}"; return out; }
    keys.forEach(function (k) { flatten(value[k], prefix ? prefix + "." + k : k, out); });
    return out;
}

function propertyDiff(a, b) {
    var fa = flatten(a, "", {});
    var fb = flatten(b, "", {});
    var keys = {};
    Object.keys(fa).forEach(function (k) { keys[k] = true; });
    Object.keys(fb).forEach(function (k) { keys[k] = true; });
    var rows = [];
    Object.keys(keys).sort().forEach(function (k) {
        var va = Object.prototype.hasOwnProperty.call(fa, k) ? fa[k] : undefined;
        var vb = Object.prototype.hasOwnProperty.call(fb, k) ? fb[k] : undefined;
        if (va !== vb) rows.push({ key: k, old: va, new: vb });
    });
    return rows;
}

// ---- Privileged asset cross-reference (optional Reports/EamDashboard dataset) -----
// window.ENTRAOPS_EAM_DATA is generated by New-EntraOpsPrivilegedEamDashboardData into
// Reports/EamDashboard/data/eam-dashboard-data.js. It's loaded here as an *optional*
// extra script (see index.html) - when absent, tier/classification cross-referencing is
// simply disabled rather than failing.
var EAM_DATA = window.ENTRAOPS_EAM_DATA || null;

// Relative privilege ordering used to compare an approver's tier against a target
// resource's tier (lower index = more privileged). Must include every tier the EAM
// dashboard dataset can emit (see EamDashboard/js/app.js TIER_ORDER). Declared before
// the object indexing below, which uses tierRank() while merging duplicate rows.
var TIER_ORDER = ["ControlPlane", "ManagementPlane", "WorkloadPlane", "UserAccess", "Unclassified"];
function tierRank(tierName) {
    var idx = TIER_ORDER.indexOf(tierName);
    return idx === -1 ? TIER_ORDER.length : idx;
}

var objectTierIndex = new Map(); // uppercased objectId -> { tierName, services: Set, displayName }
var objectUpnIndex = new Map(); // uppercased userPrincipalName -> same entry as objectTierIndex
var objectDisplayNameIndex = new Map(); // uppercased displayName -> same entry as objectTierIndex
if (EAM_DATA && Array.isArray(EAM_DATA.objects)) {
    EAM_DATA.objects.forEach(function (o) {
        if (!o.objectId) return;
        var services = new Set();
        (o.classification || []).forEach(function (c) { if (c.service) services.add(c.service); });
        var tierNames = [o.objectAdminTierLevelName];
        (o.classification || []).forEach(function (c) { tierNames.push(c.adminTierLevelName); });
        (o.roleAssignments || []).forEach(function (assignment) {
            (assignment.classification || []).forEach(function (c) {
                tierNames.push(c.adminTierLevelName);
                if (c.service) services.add(c.service);
            });
        });
        // Single min-scan instead of allocating and sorting an array per object - this runs for
        // every EAM object on the load path of five report apps.
        var TIER_RANK = { ControlPlane: 0, ManagementPlane: 1, WorkloadPlane: 2, UserAccess: 3, Unclassified: 4 };
        var effectiveTier = null, effectiveRank = 6;
        tierNames.forEach(function (t) {
            if (!t) return;
            var r = TIER_RANK[t] == null ? 5 : TIER_RANK[t];
            if (r < effectiveRank) { effectiveRank = r; effectiveTier = t; }
        });
        effectiveTier = effectiveTier || "Unclassified";
        // The dashboard dataset emits one row per (principal x role system), so the same
        // objectId can appear several times with different tiers/services. Merge rows into a
        // single entry, keeping the most privileged tier and the union of services - a
        // last-write-wins overwrite would under-report the tier of multi-system principals.
        var key = String(o.objectId).toUpperCase();
        var entry = objectTierIndex.get(key);
        if (entry) {
            services.forEach(function (s) { entry.services.add(s); });
            if (tierRank(effectiveTier) < tierRank(entry.tierName)) entry.tierName = effectiveTier;
            if (!entry.userPrincipalName && o.objectUserPrincipalName) entry.userPrincipalName = o.objectUserPrincipalName;
            if (!entry.displayName && o.objectDisplayName) entry.displayName = o.objectDisplayName;
        } else {
            entry = {
                objectId: o.objectId,
                objectType: o.objectType || "",
                userPrincipalName: o.objectUserPrincipalName || "",
                tierName: effectiveTier,
                services: services,
                displayName: o.objectDisplayName || ""
            };
            objectTierIndex.set(key, entry);
        }
        // The Tenant Governance Snapshot (UTCM/M365DSC) resolves CA policy Include/ExcludeUsers
        // to UPNs and Include/ExcludeGroups (and authentication method policy targets) to display
        // names rather than object ids - index by both so the Privileged Assets section can match
        // either shape, not just a GUID.
        if (o.objectUserPrincipalName) objectUpnIndex.set(String(o.objectUserPrincipalName).toUpperCase(), entry);
        if (o.objectDisplayName) objectDisplayNameIndex.set(String(o.objectDisplayName).toUpperCase(), entry);
    });
}

// Optional: groups referenced in captured resources that were resolved to a tier via their
// transitive membership (New-EntraOpsTenantGovernanceConfigurationAnalyzerData
// -ResolveGroupMembersForPrivilegedAssets / EntraOpsConfig.json
// ConfigurationAnalyzer.ResolveGroupMembersForPrivilegedAssets). Enabled by default and requires
// a live Microsoft Graph connection at generation time; falls back to "not resolved" when data
// is unavailable.
var resolvedGroupTierIndex = new Map(); // uppercased group id -> { tierName, displayName, totalMembers }
var resolvedGroupTierByNameIndex = new Map(); // uppercased group displayName -> same entry
if (DATA && DATA.resolvedGroupTiers && typeof DATA.resolvedGroupTiers === "object") {
    Object.keys(DATA.resolvedGroupTiers).forEach(function (id) {
        var g = DATA.resolvedGroupTiers[id];
        if (!g || !g.tierName) return;
        resolvedGroupTierIndex.set(id.toUpperCase(), g);
        if (g.displayName) resolvedGroupTierByNameIndex.set(String(g.displayName).toUpperCase(), g);
    });
}

var resolvedPolicyGroupIdsIndex = new Map(); // uppercased assignment policy id -> group ids omitted by the snapshot
if (DATA && DATA.resolvedPolicyGroupIds && typeof DATA.resolvedPolicyGroupIds === "object") {
    Object.keys(DATA.resolvedPolicyGroupIds).forEach(function (id) {
        resolvedPolicyGroupIdsIndex.set(id.toUpperCase(), DATA.resolvedPolicyGroupIds[id] || []);
    });
}

var resolvedDeviceTierIndex = new Map(); // uppercased Entra device id -> { tierName, displayName }
if (DATA && DATA.resolvedDeviceTiers && typeof DATA.resolvedDeviceTiers === "object") {
    Object.keys(DATA.resolvedDeviceTiers).forEach(function (id) {
        var device = DATA.resolvedDeviceTiers[id];
        if (device && device.tierName) resolvedDeviceTierIndex.set(id.toUpperCase(), device);
    });
}

// Sentinel/placeholder values used throughout the Tenant Governance Snapshot's Include/Exclude
// fields that are NOT an actual user/group reference and must never be resolved to a tier.
var IDENTITY_SENTINELS = { "ALL": true, "NONE": true, "GUESTSOREXTERNALUSERS": true, "ALL_USERS": true, "": true };
var GUID_SHAPE_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// Resolves a specific, deliberately-extracted identity reference (see extractIdentityIds) to a
// tier, or null if the reference is a sentinel/placeholder rather than a real user/group. The
// Tenant Governance Snapshot (UTCM/M365DSC) resolves these references to whichever shape is
// human-readable for that field - a raw object id (GUID), a user's UPN (Conditional Access
// IncludeUsers) or a group's display name (Conditional Access IncludeGroups, Authentication
// Method policy IncludeTargets) - so all three are tried in turn:
// directly classified (objectTierIndex/objectUpnIndex/objectDisplayNameIndex) -> resolved via
// group membership (resolvedGroupTierIndex, id or name) -> "UserAccess" (the default for
// anything not covered by EntraOps' classification, per the Privileged Assets coverage rule).
// A resolved group can carry more than one tier when it includes identities from multiple tiers.
function identityTiersFor(ref) {
    if (!ref) return null;
    var value = String(ref).trim();
    if (value.toUpperCase() === "ALL_USERS") return ["ControlPlane", "ManagementPlane", "UserAccess"];
    if (IDENTITY_SENTINELS[value.toUpperCase()]) return null;
    var upper = value.toUpperCase();

    if (GUID_SHAPE_RE.test(value)) {
        var viaGroupId = resolvedGroupTierIndex.get(upper);
        if (viaGroupId) return viaGroupId.tierNames || [viaGroupId.tierName];
        var direct = objectTierIndex.get(upper);
        if (direct) return [direct.tierName];
        var viaDeviceId = resolvedDeviceTierIndex.get(upper);
        if (viaDeviceId) return [viaDeviceId.tierName];
        return ["UserAccess"];
    }
    var viaUpn = objectUpnIndex.get(upper);
    if (viaUpn) return [viaUpn.tierName];
    var viaGroupName = resolvedGroupTierByNameIndex.get(upper);
    if (viaGroupName) return viaGroupName.tierNames || [viaGroupName.tierName];
    var viaDisplayName = objectDisplayNameIndex.get(upper);
    if (viaDisplayName) return [viaDisplayName.tierName];
    return ["UserAccess"];
}

function identityTierFor(ref) {
    var tiers = identityTiersFor(ref);
    return tiers && tiers[0];
}

function classifiedObjectForReference(ref) {
    if (ref == null) return null;
    var upper = String(ref).trim().toUpperCase();
    return objectTierIndex.get(upper) || objectUpnIndex.get(upper) || objectDisplayNameIndex.get(upper) || null;
}

function classifiedAssetsForReference(ref) {
    if (!ref) return [];
    var value = String(ref).trim();
    var upper = value.toUpperCase();
    if (IDENTITY_SENTINELS[upper] && upper !== "ALL_USERS") return [];

    function assetFromEntry(entry, fallbackId, fallbackName, fallbackTier) {
        if (!entry && !fallbackTier) return null;
        return {
            objectId: (entry && entry.objectId) || fallbackId || "",
            objectType: (entry && entry.objectType) || "",
            displayName: (entry && entry.displayName) || fallbackName || fallbackId || value,
            userPrincipalName: (entry && entry.userPrincipalName) || "",
            tierName: (entry && entry.tierName) || fallbackTier,
            services: entry ? Array.from(entry.services || []) : []
        };
    }

    if (upper === "ALL_USERS") {
        var allUsers = [];
        var seenUsers = new Set();
        objectTierIndex.forEach(function (entry) {
            if (String(entry.objectType).toLowerCase() !== "user" || seenUsers.has(entry.objectId)) return;
            seenUsers.add(entry.objectId);
            allUsers.push(assetFromEntry(entry));
        });
        return allUsers;
    }

    var group = resolvedGroupTierIndex.get(upper) || resolvedGroupTierByNameIndex.get(upper);
    if (group) {
        return (group.members || []).map(function (member) {
            var entry = member.id ? objectTierIndex.get(String(member.id).toUpperCase()) : null;
            return assetFromEntry(entry, member.id, member.displayName, member.tierName);
        }).filter(Boolean);
    }

    var direct = objectTierIndex.get(upper) || objectUpnIndex.get(upper) || objectDisplayNameIndex.get(upper);
    if (direct) return [assetFromEntry(direct)];
    return [{
        objectId: "",
        objectType: "Identity not listed in PrivilegedEAM",
        displayName: value,
        userPrincipalName: value.indexOf("@") > 0 ? value : "",
        tierName: "UserAccess",
        services: []
    }];
}

// Per-resource-type extraction of the raw user/group references from the specific fields that
// are documented to carry them (see TenantGovernance/Snapshots resource shapes /
// https://learn.microsoft.com/en-us/graph/utcm-entra-resources) - deliberately NOT a blanket
// GUID scan of the whole resource (that would also match the resource's own Id, CatalogId,
// PolicyId, ... and make the Privileged Assets breakdown meaningless). References are returned
// as-is (GUID, UPN or display name) together with the configuration property (field) they were
// extracted from, so the UI can explain WHY an asset is listed - identityTierFor resolves
// whichever shape they turn out to be and filters out sentinels ("All", "None", ...).
function extractIdentityRefs(resourceType, props) {
    var refs = [];
    if (!props) return refs;
    function pushRef(v, field) { if (typeof v === "string" && v.trim()) refs.push({ ref: v.trim(), field: field || "" }); }
    function pushArrayRefs(a, field) { (Array.isArray(a) ? a : []).forEach(function (v) { pushRef(v, field); }); }
    function pushTargetRefs(a, field) { (Array.isArray(a) ? a : []).forEach(function (t) { if (t) pushRef(t.Id, field); }); }
    function pushAssignmentTarget(target, field) {
        if (!target || typeof target !== "object") return;
        var targetType = String(target["@odata.type"] || target.odataType || target.Type || target.type || "").toLowerCase();
        var label = (targetType.indexOf("exclusion") !== -1 ? "Excluded assignment target (" : "Included assignment target (") + field + ")";
        ["GroupId", "groupId", "DeviceId", "deviceId", "AzureAdDeviceId", "azureAdDeviceId", "AzureADDeviceId", "ManagedDeviceId", "managedDeviceId"].forEach(function (key) {
            pushRef(target[key], label);
        });
        if ((targetType.indexOf("group") !== -1 || targetType.indexOf("device") !== -1) && target.Id) pushRef(target.Id, label);
    }
    function pushIntuneAssignmentRefs(assignments, field) {
        (Array.isArray(assignments) ? assignments : []).forEach(function (assignment) {
            if (!assignment || typeof assignment !== "object") return;
            pushAssignmentTarget(assignment.Target || assignment.target || assignment, field);
        });
    }

    var rt = String(resourceType || "").toLowerCase();
    if (rt === "microsoft.entra.conditionalaccesspolicy") {
        pushArrayRefs(props.IncludeUsers, "Included user (IncludeUsers)"); pushArrayRefs(props.IncludeGroups, "Included group (IncludeGroups)");
        // Exclusions matter as much as inclusions: the canonical CA pattern puts Tier0 break-glass
        // accounts in ExcludeUsers - a change to those exclusions must still surface the resource
        // as privileged-related (the old blanket GUID scan caught these before the field-based rewrite).
        pushArrayRefs(props.ExcludeUsers, "Excluded user (ExcludeUsers)"); pushArrayRefs(props.ExcludeGroups, "Excluded group (ExcludeGroups)");
    } else if (rt.indexOf("microsoft.entra.authenticationmethodpolicy") === 0 && rt !== "microsoft.entra.authenticationmethodpolicy") {
        // authenticationMethodPolicyAuthenticator/Email/Fido2/Sms/Software/Temporary/Voice/X509 -
        // the umbrella authenticationMethodPolicy resource itself has no target fields.
        pushTargetRefs(props.IncludeTargets, "Included target (IncludeTargets)");
    } else if (rt === "microsoft.entra.entitlementmanagementaccesspackageassignmentpolicy") {
        var requestorSettings = props.RequestorSettings || {};
        (Array.isArray(requestorSettings.AllowedRequestors) ? requestorSettings.AllowedRequestors : []).forEach(function (u) { if (u) pushRef(u.Id, "Allowed requestor (RequestorSettings.AllowedRequestors)"); });
        var approvalSettings = props.RequestApprovalSettings || {};
        (Array.isArray(approvalSettings.ApprovalStages) ? approvalSettings.ApprovalStages : []).forEach(function (stage) {
            (Array.isArray(stage.PrimaryApprovers) ? stage.PrimaryApprovers : []).forEach(function (u) { if (u) pushRef(u.Id, "Primary approver (RequestApprovalSettings.ApprovalStages)"); });
        });
        (resolvedPolicyGroupIdsIndex.get(String(props.Id || "").toUpperCase()) || []).forEach(function (v) { pushRef(v, "Group assigned via this assignment policy (resolved)"); });
    } else if (rt === "microsoft.entra.group") {
        pushArrayRefs(props.Owners, "Group owner (Owners)"); pushArrayRefs(props.Members, "Group member (Members)");
    } else if (rt === "microsoft.entra.roleeligibilityschedulerequest" || rt === "microsoft.entra.roleassignmentschedulerequest") {
        pushRef(props.PrincipalId || props.principalId, "Request principal (PrincipalId)");
        if (props.Principal || props.principal) pushRef((props.Principal || props.principal).Id, "Request principal (Principal)");
    } else if (rt === "microsoft.entra.administrativeunit") {
        var members = Array.isArray(props.Members) ? props.Members : (props.Members ? [props.Members] : []);
        members.forEach(function (member) { if (member) pushRef(member.Identity, "Administrative Unit member (Members)"); });
    } else if (rt.indexOf("microsoft.intune.") === 0) {
        pushIntuneAssignmentRefs(props.Assignments || props.assignments, "Assignments");
        pushIntuneAssignmentRefs(props.IncludeTargets || props.includeTargets, "IncludeTargets");
        pushArrayRefs(props.IncludeGroups || props.includeGroups, "Included group (IncludeGroups)");
        pushArrayRefs(props.DeviceIds || props.deviceIds, "Targeted device (DeviceIds)");
    } else if (rt === "microsoft.entra.entitlementmanagementaccesspackage") {
        (Array.isArray(props.AccessPackageResourceRoleScopes) ? props.AccessPackageResourceRoleScopes : []).forEach(function (rs) { if (rs) pushRef(rs.AccessPackageResourceOriginId, "Resource role scope origin (AccessPackageResourceRoleScopes)"); });
    }
    return refs;
}

function extractIdentityIds(resourceType, props) {
    return extractIdentityRefs(resourceType, props).map(function (entry) { return entry.ref; });
}

// =====================================================================================
// Privileged Assets: per-resource-type breakdown of which captured resources involve a
// Control Plane / Management Plane / User Access identity (shared by the Configuration
// Analyzer's Privileged Assets section).
// =====================================================================================
var privilegedAssetsCache = {};
function privilegedAssetsForSnapshot(snap) {
    var key = snap.commitSha + "|" + snap.commitDate;
    if (privilegedAssetsCache[key]) return privilegedAssetsCache[key];

    var byType = {};
    snap.resources.forEach(function (r) {
        var blob = blobContent(r.h);
        if (blob === undefined || blob === null) return;
        var props = blob.properties || {};
        if (!byType[r.type]) {
            byType[r.type] = { type: r.type, totalWithContent: 0, totalWithIdentities: 0, tiers: { ControlPlane: [], ManagementPlane: [], UserAccess: [] } };
        }
        var entry = byType[r.type];
        entry.totalWithContent++;

        var refs = extractIdentityIds(r.type, props);
        var tiersFound = {};
        refs.forEach(function (ref) {
            (identityTiersFor(ref) || []).forEach(function (tier) {
                if (tier) tiersFound[tier] = true;
            });
        });
        if (!Object.keys(tiersFound).length) return;
        entry.totalWithIdentities++;

        var name = props.DisplayName || r.name;
        Object.keys(tiersFound).forEach(function (t) {
            if (entry.tiers[t]) entry.tiers[t].push(name);
        });
    });

    var result = Object.keys(byType).map(function (t) { return byType[t]; }).sort(function (a, b) { return a.type.localeCompare(b.type); });
    privilegedAssetsCache[key] = result;
    return result;
}

var relatedObjectIdsCache = {};
// Uses the same documented identity-bearing fields as Privileged Assets so explorer
// filtering and the aggregate view cannot disagree about whether a resource involves
// an EntraOps identity.
function relatedPrivilegedObjects(hash, resourceType) {
    var cacheKey = hash + "|" + String(resourceType || "");
    if (!hash || (!objectTierIndex.size && !resolvedGroupTierIndex.size)) return null;
    if (relatedObjectIdsCache[cacheKey] !== undefined) return relatedObjectIdsCache[cacheKey];
    var blob = blobContent(hash);
    if (blob === undefined || blob === null) { relatedObjectIdsCache[cacheKey] = null; return null; }
    var tierNames = new Set(), services = new Set();
    extractIdentityIds(resourceType || blob.resourceType, blob.properties || {}).forEach(function (reference) {
        (identityTiersFor(reference) || []).forEach(function (tier) { tierNames.add(tier); });
        var upper = String(reference).toUpperCase();
        var hit = objectTierIndex.get(upper) || objectUpnIndex.get(upper) || objectDisplayNameIndex.get(upper);
        if (hit) {
            hit.services.forEach(function (service) { services.add(service); });
        } else {
            var group = resolvedGroupTierIndex.get(upper) || resolvedGroupTierByNameIndex.get(upper);
            (group && group.members || []).forEach(function (member) {
                var memberHit = member.id ? objectTierIndex.get(String(member.id).toUpperCase()) : null;
                if (memberHit) memberHit.services.forEach(function (service) { services.add(service); });
            });
        }
    });
    var result = tierNames.size ? { tierNames: tierNames, services: services } : null;
    relatedObjectIdsCache[cacheKey] = result;
    return result;
}

// =====================================================================================
// Conditional Access policy parsing (shared by Configuration Analyzer's summary stat and
// the Conditional Access Analysis app's Sankey + coverage gap checks).
// =====================================================================================
function isCaPolicyType(type) {
    return String(type).toLowerCase() === "microsoft.entra.conditionalaccesspolicy";
}

var CLIENT_APP_LABELS = {
    browser: "Browser",
    mobileAppsAndDesktopClients: "Mobile apps & desktop clients",
    exchangeActiveSync: "Exchange ActiveSync (legacy)",
    other: "Other clients (legacy auth)",
    all: "All client apps"
};
var GRANT_LABELS = {
    block: "Block access",
    mfa: "Require MFA",
    compliantDevice: "Require compliant device",
    domainJoinedDevice: "Require hybrid joined device",
    approvedApplication: "Require approved client app",
    compliantApplication: "Require app protection policy",
    passwordChange: "Require password change"
};
var APP_LABELS = {
    All: "All resources (cloud apps)",
    Office365: "Office 365",
    MicrosoftAdminPortals: "Microsoft Admin Portals",
    None: "None"
};

function normalizeState(s) {
    s = String(s || "").toLowerCase();
    if (s === "enabled") return "enabled";
    if (s === "enabledforreportingbutnotenforced") return "reportOnly";
    if (s === "disabled") return "disabled";
    return "disabled";
}

function arr(v) { return Array.isArray(v) ? v.filter(function (x) { return x !== null && x !== "" && x !== undefined; }) : []; }

// Parse one captured microsoft.entra.conditionalAccessPolicy resource (UTCM/M365DSC
// property naming - see TenantGovernance/Snapshots) into the aspect lists rendered as
// Sankey columns. Every list is non-empty so each policy always spans all columns.
function parseCaPolicy(resource, blob) {
    var p = (blob && blob.properties) ? blob.properties : {};
    var name = p.DisplayName || resource.name;
    var st = normalizeState(p.State);

    var assignments = [];
    arr(p.IncludeUsers).forEach(function (u) {
        if (u === "All") assignments.push("All users");
        else if (u === "None") return;
        else if (u === "GuestsOrExternalUsers") assignments.push("Guests / external users");
        else assignments.push("User: " + u);
    });
    arr(p.IncludeGroups).forEach(function (g) { assignments.push("Group: " + g); });
    arr(p.IncludeRoles).forEach(function (r) { assignments.push("Role: " + r); });
    if (arr(p.IncludeGuestOrExternalUserTypes).length && assignments.indexOf("All users") === -1) {
        assignments.push("Guests / external users");
    }
    if (!assignments.length) assignments.push("(no user scope)");

    var targets = [];
    arr(p.IncludeApplications).forEach(function (a) {
        if (a === "None") return;
        targets.push(APP_LABELS[a] ? APP_LABELS[a] : "App: " + a);
    });
    arr(p.IncludeUserActions).forEach(function (a) { targets.push("User action: " + a); });
    arr(p.AuthenticationContexts).forEach(function (c) { targets.push("Auth context: " + c); });
    if (arr(p.ProtocolFlows).length) targets.push("Protocol flows: " + arr(p.ProtocolFlows).join(", "));
    if (!targets.length) targets.push("(no target resource)");

    var network = [];
    arr(p.IncludeLocations).forEach(function (l) {
        if (l === "All") network.push("Any location");
        else if (l === "AllTrusted") network.push("All trusted locations");
        else network.push("Location: " + l);
    });
    if (!network.length) network.push("Any network");

    var conditions = [];
    arr(p.IncludePlatforms).forEach(function (pf) {
        conditions.push(pf === "all" ? "Any platform" : "Platform: " + pf);
    });
    var clientAppTypes = arr(p.ClientAppTypes);
    clientAppTypes.forEach(function (c) {
        if (c === "all") return;
        conditions.push(CLIENT_APP_LABELS[c] || "Client app: " + c);
    });
    arr(p.SignInRiskLevels).forEach(function (r) { conditions.push("Sign-in risk: " + r); });
    arr(p.UserRiskLevels).forEach(function (r) { conditions.push("User risk: " + r); });
    arr(p.ServicePrincipalRiskLevels).forEach(function (r) { conditions.push("SP risk: " + r); });
    if (p.DeviceFilterRule) conditions.push("Device filter rule");
    if (arr(p.InsiderRiskLevels || p.InsiderRiskTypes).length) conditions.push("Insider risk");
    if (!conditions.length) conditions.push("Any condition");

    var sessionControls = [];
    if (p.SignInFrequencyIsEnabled) sessionControls.push("Sign-in frequency: " + (p.SignInFrequencyValue ? p.SignInFrequencyValue + " " + (p.SignInFrequencyType || "") : (p.SignInFrequencyInterval || "enabled")));
    if (p.PersistentBrowserIsEnabled) sessionControls.push("Persistent browser: " + (p.PersistentBrowserMode || "enabled"));
    if (p.CloudAppSecurityIsEnabled) sessionControls.push("Cloud App Security: " + (p.CloudAppSecurityType || "enabled"));
    if (p.ApplicationEnforcedRestrictionsIsEnabled) sessionControls.push("App enforced restrictions");
    if (p.SecureSignInSessionIsEnabled) sessionControls.push("Token protection");

    var grants = [];
    arr(p.BuiltInControls).forEach(function (g) { grants.push(GRANT_LABELS[g] || g); });
    if (p.AuthenticationStrength) grants.push("Auth strength: " + p.AuthenticationStrength);
    var grantKind; // used for link coloring + filters
    if (grants.some(function (g) { return g === "Block access"; })) grantKind = "block";
    else if (grants.length) grantKind = "grant";
    else if (sessionControls.length) { grants.push("Session controls only"); grantKind = "session"; }
    else { grants.push("No control (monitor only)"); grantKind = "none"; }

    var exclusions = [];
    arr(p.ExcludeUsers).forEach(function (u) { exclusions.push("User: " + u); });
    arr(p.ExcludeGroups).forEach(function (g) { exclusions.push("Group: " + g); });
    arr(p.ExcludeRoles).forEach(function (r) { exclusions.push("Role: " + r); });
    arr(p.ExcludeGuestOrExternalUserTypes).forEach(function (t) { exclusions.push("Guest type: " + t); });
    arr(p.ExcludeLocations).forEach(function (l) { exclusions.push("Location: " + l); });
    arr(p.ExcludePlatforms).forEach(function (pf) { exclusions.push("Platform: " + pf); });
    arr(p.ExcludeApplications).forEach(function (a) { exclusions.push("App: " + a); });

    return {
        id: p.Id || resource.p,
        name: name,
        state: st,
        raw: p,
        resource: resource,
        assignments: assignments,
        targets: targets,
        network: network,
        conditions: conditions,
        grants: grants,
        grantKind: grantKind,
        grantOperator: p.GrantControlOperator || "",
        sessionControls: sessionControls,
        exclusions: exclusions,
        clientAppTypes: clientAppTypes.length ? clientAppTypes : ["all"],
        includesAllUsers: arr(p.IncludeUsers).indexOf("All") !== -1,
        includesAllApps: arr(p.IncludeApplications).indexOf("All") !== -1,
        includedRoles: arr(p.IncludeRoles),
        signInRiskLevels: arr(p.SignInRiskLevels),
        userRiskLevels: arr(p.UserRiskLevels)
    };
}

var caPolicyCache = {};
function caPoliciesForSnapshot(snap) {
    var key = snap.commitSha + "|" + snap.commitDate;
    if (caPolicyCache[key]) return caPolicyCache[key];
    var policies = [];
    snap.resources.forEach(function (r) {
        if (!isCaPolicyType(r.type)) return;
        var blob = blobContent(r.h);
        if (blob === undefined || blob === null) return;
        policies.push(parseCaPolicy(r, blob));
    });
    policies.sort(function (a, b) { return a.name.localeCompare(b.name); });
    caPolicyCache[key] = policies;
    return policies;
}
