/*
 * EntraOps EIDSCA Findings
 *
 * Evaluates EIDSCA (Entra ID Security Config Analyzer, github.com/Cloud-Architekt/AzureAD-Attack-Defense)
 * checks against the properties already captured by an EntraOps Tenant Governance snapshot
 * (see Reports/ConfigurationAnalyzer, generated by New-EntraOpsTenantGovernanceConfigurationAnalyzerData).
 *
 * Reuses the snapshot/blob parsing model from ../ConfigurationAnalyzer/js/core.js (loaded
 * before this file - see index.html). The curated EIDSCA control catalog
 * (js/eidsca-controls.js) is a fixed reference dataset, not a generated build artifact.
 *
 * Three views, all driven by the same evaluateSnapshot() model:
 *   - Checks: collapsible per-area results for one selected snapshot (default view).
 *   - Trend: how ok/warn/info/unknown counts evolved across every snapshot in the dataset.
 *   - Compare: side-by-side diff of two snapshots, controls whose status changed only.
 */
(function () {
    "use strict";

    var excludedFindingIds = new Set((DATA && Array.isArray(DATA.eidscaExcludedFindings) ? DATA.eidscaExcludedFindings : []).map(String));

    var eidscaState = {
        view: "checks",
        snapshotIdx: -1,
        compareAIdx: -1,
        compareBIdx: -1,
        statusFilter: "",
        severityFilter: "",
        collapsed: {} // controlId -> bool, persists across re-renders/snapshot switches
    };

    var EIDSCA_CONTROLS = window.ENTRAOPS_EIDSCA_CONTROLS || null;
    var EIDSCA_ICONS = { ok: "\u2713", warn: "!", info: "i", unknown: "?" };
    var STATUS_ORDER = ["warn", "unknown", "info", "ok"];

    // EIDSCA's `Name` values are raw Microsoft Graph camelCase property names/paths, while the
    // Tenant Governance Snapshot (UTCM/M365DSC-based) sometimes flattens/renames or PascalCases
    // them. Resolve case-insensitively so a control still matches regardless of casing, and
    // treat an unresolved path as "unknown" rather than a false pass/fail.
    function resolveEidscaPath(obj, path) {
        var result = resolveEidscaPathWalk(obj, path);
        // Include/ExcludeTargets are WRITE-optional in the captured snapshot: when nothing is
        // included/excluded, M365DSC/UTCM omits the property entirely instead of emitting an
        // empty array (verified against real authenticationMethodPolicy* snapshots) - a path
        // through one of these segments that fails to resolve means "empty scope", not "unknown
        // property", so it's treated as [] rather than undefined.
        if (result === undefined && /(^|\.)(includetargets|excludetargets)(\.|$)/i.test(path)) {
            return [];
        }
        return result;
    }

    function resolveEidscaPathWalk(obj, path) {
        var segments = path.split(".");
        var cur = obj;
        for (var i = 0; i < segments.length; i++) {
            if (cur === null || cur === undefined || typeof cur !== "object") return undefined;
            var seg = segments[i].toLowerCase();
            if (Array.isArray(cur)) {
                // Property lives inside each array item (e.g. IncludeTargets[].TargetedAuthenticationMethod) -
                // collect distinct values across items instead of indexing.
                var vals = [];
                cur.forEach(function (item) {
                    if (item && typeof item === "object") {
                        var ik;
                        Object.keys(item).some(function (k) { if (k.toLowerCase() === seg) { ik = k; return true; } return false; });
                        if (ik !== undefined) vals.push(item[ik]);
                    }
                });
                if (!vals.length) return undefined;
                cur = vals.length === 1 ? vals[0] : vals;
                continue;
            }
            var matchKey;
            Object.keys(cur).some(function (k) { if (k.toLowerCase() === seg) { matchKey = k; return true; } return false; });
            if (matchKey === undefined) return undefined;
            cur = cur[matchKey];
        }
        return cur;
    }

    // Some controls expose an M365DSC-friendly enum/name (e.g. authorizationPolicy's
    // "GuestUserRole": "Guest") instead of the raw Graph value EIDSCA compares against (a role
    // template GUID) - c.valueMap translates the snapshot value before evaluation/display.
    function translateValue(rawVal, c) {
        if (rawVal === undefined || !c.valueMap) return rawVal;
        var key = String(rawVal).toLowerCase();
        return Object.prototype.hasOwnProperty.call(c.valueMap, key) ? c.valueMap[key] : rawVal;
    }

    function evalEidscaControl(currentValue, recommendedValue) {
        if (currentValue === undefined) return "unknown";
        if (!recommendedValue) return "info";
        var allowList = null;
        var m = String(recommendedValue).match(/^@\((.*)\)$/);
        if (m) {
            allowList = [];
            var re = /'([^']*)'|"([^"]*)"/g, mm;
            while ((mm = re.exec(m[1]))) allowList.push(mm[1] !== undefined ? mm[1] : mm[2]);
        }
        // List-valued properties (e.g. PermissionGrantPolicyIdsAssignedToDefaultUserRole) are
        // "does the list contain the expected value", not a whole-array string comparison.
        var isEmpty = currentValue === null || currentValue === "" || (Array.isArray(currentValue) && currentValue.length === 0);
        var curValues = Array.isArray(currentValue)
            ? currentValue.map(function (v) { return String(v).toLowerCase(); })
            : [String(currentValue).toLowerCase()];
        if (allowList) {
            var ok = allowList.some(function (v) {
                return curValues.indexOf(v.toLowerCase()) !== -1 || (v === "" && isEmpty);
            });
            return ok ? "ok" : "warn";
        }
        return curValues.indexOf(String(recommendedValue).toLowerCase()) !== -1 ? "ok" : "warn";
    }

    // ---- Evaluate one snapshot against the full covered control catalog ----------------
    // Shared by the Checks view, the Trend chart and the Compare diff - keeps the "what does
    // this snapshot pass/fail/miss" logic in exactly one place.
    // Per-snapshot evaluation memo: the dataset and the exclusion list are immutable for the
    // lifetime of the page, so the same snapshot always evaluates to the same result - but
    // renderChecksView re-evaluated it on every status tile / severity / expand-all click, and
    // the Trend view re-evaluated every snapshot on every visit. Keyed by snapshot object
    // (WeakMap), mirroring the sibling apps' per-snapshot caches (pimCache, caPolicyCache).
    var evalCache = new WeakMap();
    function evaluateSnapshot(snap) {
        var cached = evalCache.get(snap);
        if (cached) return cached;
        var result = evaluateSnapshotUncached(snap);
        evalCache.set(snap, result);
        return result;
    }

    function evaluateSnapshotUncached(snap) {
        var counts = { ok: 0, warn: 0, info: 0, unknown: 0 };
        var severityCounts = {}; // severity -> { ok, warn, info, unknown }
        var reachableCount = 0; // controls where a resource+blob existed, whether or not the property resolved
        var areaResults = [];

        function tally(c, status, reachable) {
            counts[status]++;
            if (reachable) reachableCount++;
            var sev = c.severity || "Unspecified";
            if (!severityCounts[sev]) severityCounts[sev] = { ok: 0, warn: 0, info: 0, unknown: 0 };
            severityCounts[sev][status]++;
        }

        EIDSCA_CONTROLS.covered.forEach(function (area) {
            var utcmTypeLower = area.utcmType.toLowerCase();
            var resources = snap.resources.filter(function (r) { return String(r.type).toLowerCase() === utcmTypeLower; });
            var controls = area.controls.filter(function (control) { return !excludedFindingIds.has(control.checkId); });
            var resultArea = Object.assign({}, area, { controls: controls });
            var areaStats = { ok: 0, warn: 0, info: 0, unknown: 0 };
            var resourceBlocks = [];

            if (!resources.length) {
                controls.forEach(function (c) { tally(c, "unknown", false); areaStats.unknown++; });
                areaResults.push({ area: resultArea, noResourceType: true, resourceBlocks: [], areaStats: areaStats });
                return;
            }

            resources.forEach(function (r) {
                var blob = blobContent(r.h);
                if (blob === undefined || blob === null) {
                    controls.forEach(function (c) { tally(c, "unknown", false); areaStats.unknown++; });
                    resourceBlocks.push({ blobMissing: true, controlResults: [] });
                    return;
                }
                var props = (blob && blob.properties) ? blob.properties : {};
                var controlResults = controls.map(function (c) {
                    var rawVal = resolveEidscaPath(props, c.name);
                    var curVal = translateValue(rawVal, c);
                    var status = (rawVal === undefined && c.notCapturedNote) ? "info" : evalEidscaControl(curVal, c.recommendedValue);
                    tally(c, status, true);
                    areaStats[status]++;
                    return { control: c, status: status, rawVal: rawVal, curVal: curVal };
                });
                resourceBlocks.push({ blobMissing: false, resource: r, controlResults: controlResults });
            });

            areaResults.push({ area: resultArea, noResourceType: false, resourceBlocks: resourceBlocks, areaStats: areaStats });
        });

        return { areaResults: areaResults, counts: counts, severityCounts: severityCounts, reachableCount: reachableCount };
    }

    function totalCoveredControls() {
        var n = 0;
        EIDSCA_CONTROLS.covered.forEach(function (a) {
            n += a.controls.filter(function (control) { return !excludedFindingIds.has(control.checkId); }).length;
        });
        return n;
    }

    function totalNotCoveredControls() {
        var n = 0;
        EIDSCA_CONTROLS.notCovered.forEach(function (a) { n += a.controlCount; });
        return n;
    }

    // ---- MITRE ATT&CK badges -------------------------------------------------------------
    function mitreTacticChip(tactic) {
        var parts = tactic.split(" - ");
        var code = parts[0].trim();
        return '<a class="chip attack" href="https://attack.mitre.org/tactics/' + esc(code) + '/" target="_blank" rel="noopener noreferrer" title="MITRE ATT&amp;CK Tactic: ' + esc(tactic) + '">' + esc(code) + "</a>";
    }

    function mitreTechniqueChip(tech) {
        var urlPath = tech.replace(".", "/");
        return '<a class="chip attack" href="https://attack.mitre.org/techniques/' + esc(urlPath) + '/" target="_blank" rel="noopener noreferrer" title="MITRE ATT&amp;CK Technique: ' + esc(tech) + '">' + esc(tech) + "</a>";
    }

    // ---- Checks view: per-control / per-area rendering -----------------------------------
    function renderAreaGapRow(area, kind) {
        if (kind === "type-missing") {
            return '<div class="ca-gap-row"><span class="ca-gap-icon warn">!</span><div><div class="ca-gap-title">' + esc(area.controlName) + '</div><div class="ca-gap-detail">Resource type <code>' + esc(area.utcmType) + "</code> is not captured in this snapshot - add it to <code>TenantGovernanceSnapshot.ResourcesToInclude</code> to evaluate these " + area.controls.length + " check(s).</div></div></div>";
        }
        return '<div class="ca-gap-row"><span class="ca-gap-icon unknown">?</span><div><div class="ca-gap-title">' + esc(area.controlName) + "</div><div class=\"ca-gap-detail\">Resource content not embedded for this snapshot - regenerate with a higher <code>-MaxDetailedSnapshots</code>.</div></div></div>";
    }

    function renderControlRow(cr, areaIndex, resourceIndex) {
        var c = cr.control, status = cr.status, rawVal = cr.rawVal, curVal = cr.curVal;
        var curDisplay;
        if (rawVal === undefined && c.notCapturedNote) {
            curDisplay = "<i>not covered by Tenant Governance Snapshot yet</i>";
        } else if (curVal === undefined) {
            curDisplay = "<i>property not found</i>";
        } else {
            curDisplay = esc(typeof curVal === "object" ? JSON.stringify(curVal) : String(curVal));
            if (c.valueMap && rawVal !== undefined && String(rawVal) !== String(curVal)) {
                curDisplay += ' <span class="muted">(raw: ' + esc(String(rawVal)) + ")</span>";
            }
        }
        var detail = "Current: " + curDisplay;
        if (c.recommendedValue) detail += " &middot; Recommended: " + esc(c.recommendedValue);
        if (rawVal === undefined && c.notCapturedNote) detail += "<br/>" + esc(c.notCapturedNote);
        else if (c.recommendation) detail += "<br/>" + esc(c.recommendation);
        if (c.portalDeepLink) detail += ' &middot; <a href="' + esc(c.portalDeepLink) + '" target="_blank" rel="noopener noreferrer">Open in Entra admin center</a>';
        detail += ' &middot; <button type="button" class="btn small" data-eidsca-source="' + areaIndex + "|" + resourceIndex + "|" + esc(c.checkId) + '">Inspect source resource</button>';

        var mitreChips = [];
        (c.mitreTactic || []).forEach(function (t) { mitreChips.push(mitreTacticChip(t)); });
        (c.mitreTechnique || []).forEach(function (t) { mitreChips.push(mitreTechniqueChip(t)); });
        var mitreHtml = mitreChips.length ? '<div class="eidsca-row-mitre">' + mitreChips.join(" ") + "</div>" : "";
        var sevHtml = c.severity ? '<span class="eidsca-severity eidsca-severity-' + esc(String(c.severity).toLowerCase()) + '">' + esc(c.severity) + "</span>" : "";

        return '<div class="ca-gap-row"><span class="ca-gap-icon ' + status + '">' + EIDSCA_ICONS[status] + '</span><div><div class="ca-gap-title">' + esc(c.displayName || c.name) + ' <span class="muted" style="font-size:11px;">(' + esc(c.checkId) + ")</span> " + sevHtml + " " + EntraOpsReportUtils.reviewControl("eidsca-findings", c.checkId, status === "ok" ? "Remediated" : "Open", status === "ok") + '</div><div class="ca-gap-detail">' + detail + "</div>" + mitreHtml + "</div></div>";
    }

    function areaBodyHtml(ar, areaIndex) {
        if (!ar.area.controls.length) return "";
        if (ar.noResourceType) return renderAreaGapRow(ar.area, "type-missing");
        var html = "";
        ar.resourceBlocks.forEach(function (rb, resourceIndex) {
            if (rb.blobMissing) { html += renderAreaGapRow(ar.area, "blob-missing"); return; }
            rb.controlResults.forEach(function (cr) {
                var severity = cr.control.severity || "Unspecified";
                if ((!eidscaState.statusFilter || cr.status === eidscaState.statusFilter) &&
                    (!eidscaState.severityFilter || severity === eidscaState.severityFilter)) html += renderControlRow(cr, areaIndex, resourceIndex);
            });
        });
        return html;
    }

    function areaStatPillsHtml(st) {
        return ["warn", "unknown", "info", "ok"].map(function (s) {
            return st[s] ? '<span class="eidsca-stat-pill ' + s + '">' + EIDSCA_ICONS[s] + " " + st[s] + "</span>" : "";
        }).join("");
    }

    function setAllCollapsed(areaResults, val) {
        areaResults.forEach(function (ar) { eidscaState.collapsed[ar.area.controlId] = val; });
    }

    function renderQuickNav(areaResults) {
        var links = areaResults.map(function (ar, idx) {
            if (!ar.area.controls.length) return "";
            var st = ar.areaStats;
            var dotClass = st.warn ? "warn" : (st.unknown ? "unknown" : "ok");
            return '<a class="eidsca-navlink" href="#eidsca-area-' + idx + '"><span class="eidsca-navdot ' + dotClass + '"></span>' + esc(ar.area.controlName) + "</a>";
        }).join("");
        return '<div class="eidsca-quicknav"><div class="eidsca-quicknav-actions">' +
            '<button type="button" class="btn small" id="eidscaExpandAll">Expand all</button>' +
            '<button type="button" class="btn small" id="eidscaCollapseAll">Collapse all</button>' +
            '</div><div class="eidsca-quicknav-links">' + links + "</div></div>";
    }

    function renderDashboard(evalResult) {
        var el = $("eidscaDashboard");
        if (!el) return;
        el.classList.remove("hidden");
        var c = evalResult.counts;
        var tiles = [
            { key: "ok", label: "Passing", value: c.ok },
            { key: "warn", label: "Failing", value: c.warn },
            { key: "info", label: "Informational / not evaluable", value: c.info },
            { key: "unknown", label: "Unknown (gap)", value: c.unknown }
        ].map(function (t) {
            var accentColor = { ok: "#0e700e", warn: "#a4262c", info: "#0078d4", unknown: "#a19f9d" }[t.key];
            var selected = eidscaState.statusFilter === t.key;
            return '<button type="button" class="stat" data-eidsca-status="' + t.key + '" aria-pressed="' + selected + '"><div class="stat-accent" style="background:' + accentColor + ';"></div><div class="stat-label">' + esc(t.label) + '</div><div class="stat-value">' + t.value + "</div></button>";
        }).join("");

        var sevRows = Object.keys(evalResult.severityCounts)
            .sort(function (a, b) { return a.localeCompare(b); })
            .map(function (sev) {
                var s = evalResult.severityCounts[sev];
                var total = s.ok + s.warn + s.info + s.unknown;
                if (!total) return "";
                var selected = eidscaState.severityFilter === sev;
                return '<button type="button" class="eidsca-sev-row' + (selected ? ' selected' : '') + '" data-eidsca-severity="' + esc(sev) + '" aria-pressed="' + selected + '"><span class="eidsca-severity eidsca-severity-' + esc(sev.toLowerCase()) + '">' + esc(sev) + '</span>' +
                    '<span class="eidsca-sev-bar"><span class="ok" style="width:' + (100 * s.ok / total) + '%"></span><span class="warn" style="width:' + (100 * s.warn / total) + '%"></span><span class="info" style="width:' + (100 * s.info / total) + '%"></span><span class="unknown" style="width:' + (100 * s.unknown / total) + '%"></span></span>' +
                    '<span class="muted" style="font-size:12px;">' + s.ok + ' ok &middot; ' + s.warn + ' failing &middot; ' + s.info + ' info &middot; ' + s.unknown + ' unknown</span></button>';
            }).join("");

        el.innerHTML = '<div class="grid cols-4" style="margin-bottom:14px;">' + tiles + '</div>' +
            (sevRows ? '<div class="eidsca-sev-breakdown">' + sevRows + '</div>' : "");
        el.querySelectorAll("[data-eidsca-status]").forEach(function (tile) {
            tile.addEventListener("click", function () {
                var status = tile.getAttribute("data-eidsca-status");
                eidscaState.statusFilter = eidscaState.statusFilter === status ? "" : status;
                renderChecksView();
            });
        });
        el.querySelectorAll("[data-eidsca-severity]").forEach(function (row) {
            row.addEventListener("click", function () {
                var severity = row.getAttribute("data-eidsca-severity");
                eidscaState.severityFilter = eidscaState.severityFilter === severity ? "" : severity;
                renderChecksView();
            });
        });
    }

    function renderChecksView() {
        var el = $("eidscaBody");
        if (!el) return;
        if (!EIDSCA_CONTROLS) {
            el.innerHTML = '<div class="muted">EIDSCA control catalog (<code>js/eidsca-controls.js</code>) not loaded.</div>';
            return;
        }
        var snap = eidscaState.snapshotIdx >= 0 ? snapshots[eidscaState.snapshotIdx] : null;
        if (!snap) {
            el.innerHTML = '<div class="muted">Select a detailed snapshot above to evaluate EIDSCA checks against it.</div>';
            $("eidscaDashboard").classList.add("hidden");
            return;
        }

        var evalResult = evaluateSnapshot(snap);
        renderDashboard(evalResult);

        var filteredCount = 0;
        evalResult.areaResults.forEach(function (area) {
            area.resourceBlocks.forEach(function (block) {
                (block.controlResults || []).forEach(function (result) {
                    var severity = result.control.severity || "Unspecified";
                    if ((!eidscaState.statusFilter || result.status === eidscaState.statusFilter) &&
                        (!eidscaState.severityFilter || severity === eidscaState.severityFilter)) filteredCount++;
                });
            });
        });
        $("eidscaFreshness").textContent = EntraOpsReportUtils.freshnessText(DATA, snap);
        $("eidscaFilterSummary").textContent = " · " + filteredCount + " check result(s) shown";

        var totalControls = totalCoveredControls() + totalNotCoveredControls();
        var summaryHtml = '<p class="muted" style="margin-bottom:12px;">' + evalResult.reachableCount + " of " + totalControls + " EIDSCA checks evaluated from this snapshot (" +
            Math.round(100 * evalResult.reachableCount / totalControls) + '%). Checks sourced from <a href="https://github.com/Cloud-Architekt/AzureAD-Attack-Defense" target="_blank" rel="noopener noreferrer">EIDSCA</a> - "ok" reflects only what the snapshot captured, not a full assessment.</p>';

        var areaBlocks = "";
        evalResult.areaResults.forEach(function (ar, idx) {
            var bodyHtml = areaBodyHtml(ar, idx);
            if (!bodyHtml) return;
            var isCollapsed = eidscaState.collapsed[ar.area.controlId] !== false;
            var mitreHtml = (ar.area.mitreTactic || []).map(mitreTacticChip).join(" ");
            areaBlocks += '<div class="eidsca-area" id="eidsca-area-' + idx + '">' +
                '<button type="button" class="eidsca-area-head" data-idx="' + idx + '" aria-expanded="' + (!isCollapsed) + '">' +
                '<span class="eidsca-area-chevron">' + (isCollapsed ? "&#9656;" : "&#9662;") + "</span>" +
                '<span class="eidsca-area-title">' + esc(ar.area.controlName) + "</span>" +
                (mitreHtml ? '<span class="eidsca-area-mitre">' + mitreHtml + "</span>" : "") +
                '<span class="eidsca-area-stats">' + areaStatPillsHtml(ar.areaStats) + "</span>" +
                "</button>" +
                '<div class="eidsca-area-body' + (isCollapsed ? " collapsed" : "") + '" id="eidsca-body-' + idx + '">' + bodyHtml + "</div>" +
                "</div>";
        });

        var notCoveredCount = totalNotCoveredControls();
        var notCoveredHtml = '<div class="muted" style="font-size:12px;margin-top:4px;">Not evaluable from the Tenant Governance Snapshot today (' + notCoveredCount + " EIDSCA check(s), no matching UTCM resource type yet): " +
            EIDSCA_CONTROLS.notCovered.map(function (a) { return esc(a.controlName) + " (" + a.controlCount + ", needs <code>" + esc(a.endpoint) + "</code>)"; }).join(", ") + ".</div>";

        el.innerHTML = summaryHtml + renderQuickNav(evalResult.areaResults) + areaBlocks + notCoveredHtml;
        EntraOpsReportUtils.bindReviewControls(el);

        el.querySelectorAll("[data-eidsca-source]").forEach(function (button) {
            button.addEventListener("click", function () {
                var parts = button.getAttribute("data-eidsca-source").split("|");
                var area = evalResult.areaResults[Number(parts[0])];
                var block = area && area.resourceBlocks[Number(parts[1])];
                var result = block && block.controlResults.filter(function (item) { return item.control.checkId === parts[2]; })[0];
                if (!area || !block || !result) return;
                var resource = block.resource || {};
                window.EntraOpsObjectInspector.open({
                    title: result.control.displayName || result.control.name || "EIDSCA source resource",
                    fields: [
                        { label: "Check ID", value: result.control.checkId },
                        { label: "Evaluation", value: result.status },
                        { label: "Resource type", value: resource.type },
                        { label: "Resource path", value: resource.p },
                        { label: "Current value", value: typeof result.curVal === "object" ? JSON.stringify(result.curVal) : result.curVal },
                        { label: "Recommended value", value: result.control.recommendedValue }
                    ],
                    related: result.control.recommendation ? [result.control.recommendation] : []
                });
            });
        });

        el.querySelectorAll(".eidsca-area-head").forEach(function (head) {
            head.addEventListener("click", function () {
                var idx = Number(head.getAttribute("data-idx"));
                var controlId = evalResult.areaResults[idx].area.controlId;
                var collapsed = !eidscaState.collapsed[controlId];
                eidscaState.collapsed[controlId] = collapsed;
                var body = $("eidsca-body-" + idx);
                body.classList.toggle("collapsed", collapsed);
                head.setAttribute("aria-expanded", String(!collapsed));
                head.querySelector(".eidsca-area-chevron").innerHTML = collapsed ? "&#9656;" : "&#9662;";
            });
        });
        var expandAllBtn = $("eidscaExpandAll"), collapseAllBtn = $("eidscaCollapseAll");
        if (expandAllBtn) expandAllBtn.addEventListener("click", function () { setAllCollapsed(evalResult.areaResults, false); renderChecksView(); });
        if (collapseAllBtn) collapseAllBtn.addEventListener("click", function () { setAllCollapsed(evalResult.areaResults, true); renderChecksView(); });
    }

    // ---- Trend view: ok/warn/info/unknown counts across every snapshot ------------------
    // Not limited to "detailed" snapshots - a resource's git blob is content-addressed, so it
    // resolves via blobContent() as long as *any* commit embedded that exact content, even if
    // this particular commit wasn't flagged hasDetail.
    var trendPointsCache = null;
    function computeTrendPoints() {
        // Dataset is immutable - compute once, reuse on every Trend visit (the per-snapshot
        // evaluations are additionally served by evalCache).
        if (trendPointsCache) return trendPointsCache;
        var points = [];
        snapshots.forEach(function (snap, idx) {
            var evalResult = evaluateSnapshot(snap);
            if (!evalResult.reachableCount) return; // nothing evaluable in this snapshot - skip from the trend
            points.push({ idx: idx, date: snap.commitDate, counts: evalResult.counts, reachableCount: evalResult.reachableCount });
        });
        trendPointsCache = points;
        return points;
    }

    function renderTrendView() {
        var el = $("eidscaTrendBody");
        if (!el) return;
        if (!EIDSCA_CONTROLS) { el.innerHTML = '<div class="muted">EIDSCA control catalog not loaded.</div>'; return; }
        var points = computeTrendPoints();
        if (points.length < 2) {
            el.innerHTML = '<div class="muted">Not enough evaluable snapshots yet to plot a trend (need at least 2 with embedded resource content).</div>';
            return;
        }

        var width = 900, height = 260, padL = 42, padR = 16, padT = 16, padB = 28;
        var plotW = width - padL - padR, plotH = height - padT - padB;
        var maxV = 0;
        points.forEach(function (p) { maxV = Math.max(maxV, p.counts.ok + p.counts.warn + p.counts.info + p.counts.unknown); });
        maxV = maxV || 1;

        var minDate = new Date(points[0].date).getTime(), maxDate = new Date(points[points.length - 1].date).getTime();
        var dateSpan = Math.max(1, maxDate - minDate);
        function xAt(d) { return padL + ((new Date(d).getTime() - minDate) / dateSpan) * plotW; }
        function yAt(v) { return padT + plotH - (v / maxV) * plotH; }

        var series = [
            { key: "ok", color: "#0e700e" },
            { key: "warn", color: "#c07807" },
            { key: "info", color: "#0078d4" },
            { key: "unknown", color: "#a19f9d" }
        ];

        var gridLines = 4, grid = "";
        for (var i = 0; i <= gridLines; i++) {
            var y = padT + (plotH / gridLines) * i;
            var val = Math.round(maxV - (maxV / gridLines) * i);
            grid += '<line x1="' + padL + '" y1="' + y + '" x2="' + (width - padR) + '" y2="' + y + '" stroke="#edebe9" stroke-width="1"/>' +
                '<text x="' + (padL - 6) + '" y="' + (y + 4) + '" text-anchor="end" font-size="10" fill="#605e5c">' + val + "</text>";
        }

        var paths = "", dots = "";
        series.forEach(function (s) {
            var d = points.map(function (p, i) { return (i === 0 ? "M" : "L") + " " + xAt(p.date).toFixed(1) + " " + yAt(p.counts[s.key]).toFixed(1); }).join(" ");
            paths += '<path d="' + d + '" fill="none" stroke="' + s.color + '" stroke-width="2"/>';
            points.forEach(function (p) {
                dots += '<circle cx="' + xAt(p.date).toFixed(1) + '" cy="' + yAt(p.counts[s.key]).toFixed(1) + '" r="3" fill="' + s.color + '" stroke="#fff" stroke-width="1"><title>' +
                    esc(s.key) + ": " + p.counts[s.key] + " (" + esc(fmtDateShort(p.date)) + ")</title></circle>";
            });
        });

        var legend = series.map(function (s) {
            return '<div class="li"><span class="sw" style="background:' + s.color + '"></span><span class="nm">' + esc(s.key) + "</span></div>";
        }).join("");

        var svg = '<svg width="' + width + '" height="' + height + '" viewBox="0 0 ' + width + " " + height + '" preserveAspectRatio="xMidYMid meet" style="max-width:100%;height:auto;">' + grid +
            '<text x="' + padL + '" y="' + (height - 6) + '" font-size="10" fill="#605e5c">' + esc(fmtDateShort(points[0].date)) + "</text>" +
            '<text x="' + (width - padR) + '" y="' + (height - 6) + '" text-anchor="end" font-size="10" fill="#605e5c">' + esc(fmtDateShort(points[points.length - 1].date)) + "</text>" +
            paths + dots + "</svg>";

        el.innerHTML = '<p class="muted" style="margin-bottom:8px;">Evaluated EIDSCA check outcomes across ' + points.length + " snapshot(s) with embedded resource content.</p>" +
            svg + '<div class="donut-legend" style="margin-top:8px;">' + legend + "</div>";
    }

    // ---- Compare view: two snapshots side by side, changed controls only ----------------
    function renderCompareView() {
        var el = $("eidscaCompareBody");
        if (!el) return;
        if (!EIDSCA_CONTROLS) { el.innerHTML = '<div class="muted">EIDSCA control catalog not loaded.</div>'; return; }
        var a = eidscaState.compareAIdx, b = eidscaState.compareBIdx;
        if (a < 0 || b < 0 || a === b) {
            el.innerHTML = '<div class="muted">Choose two different snapshots above to compare their EIDSCA results.</div>';
            return;
        }
        var evalA = evaluateSnapshot(snapshots[a]), evalB = evaluateSnapshot(snapshots[b]);
        if (!evalA.reachableCount || !evalB.reachableCount) {
            el.innerHTML = '<div class="muted">One of the selected snapshots has no embedded resource content to evaluate.</div>';
            return;
        }

        function flatten(evalResult) {
            var map = {};
            evalResult.areaResults.forEach(function (ar) {
                ar.resourceBlocks.forEach(function (rb) {
                    if (rb.blobMissing) return;
                    rb.controlResults.forEach(function (cr) { map[cr.control.checkId] = cr; });
                });
            });
            return map;
        }
        var mapA = flatten(evalA), mapB = flatten(evalB);
        var rows = "", changedCount = 0, sameCount = 0;
        function displayValue(value) {
            return typeof value === "object" ? JSON.stringify(value) : String(value);
        }
        EIDSCA_CONTROLS.covered.forEach(function (area) {
            area.controls.forEach(function (c) {
                var crA = mapA[c.checkId], crB = mapB[c.checkId];
                if (!crA || !crB) return;
                if (crA.status === crB.status && displayValue(crA.curVal) === displayValue(crB.curVal)) { sameCount++; return; }
                changedCount++;
                var dispA = crA.curVal === undefined ? "<i>not found</i>" : esc(displayValue(crA.curVal));
                var dispB = crB.curVal === undefined ? "<i>not found</i>" : esc(displayValue(crB.curVal));
                rows += '<tr><td>' + esc(c.displayName || c.name) + ' <span class="muted" style="font-size:11px;">(' + esc(c.checkId) + ')</span></td>' +
                    '<td><span class="ca-gap-icon ' + crA.status + '" style="width:18px;height:18px;font-size:11px;">' + EIDSCA_ICONS[crA.status] + "</span> " + dispA + "</td>" +
                    '<td><span class="ca-gap-icon ' + crB.status + '" style="width:18px;height:18px;font-size:11px;">' + EIDSCA_ICONS[crB.status] + "</span> " + dispB + "</td></tr>";
            });
        });

        var table = changedCount
            ? '<table class="ca-diff-table"><thead><tr><th>Check</th><th>' + esc(snapshotLabel(snapshots[a], a)) + "</th><th>" + esc(snapshotLabel(snapshots[b], b)) + "</th></tr></thead><tbody>" + rows + "</tbody></table>"
            : '<div class="muted">No differences in evaluated check status/value between these two snapshots.</div>';

        el.innerHTML = '<p class="muted" style="margin-bottom:8px;">' + changedCount + " changed, " + sameCount + " unchanged (out of the checks evaluable in both snapshots).</p>" + table;
    }

    // ---- View switching / pickers --------------------------------------------------------
    function renderSnapshotPicker() {
        var sel = $("eidscaSnapshot");
        var idxs = detailedSnapshotIdxs();
        var html = "";
        idxs.forEach(function (i) {
            html += '<option value="' + i + '"' + (i === eidscaState.snapshotIdx ? " selected" : "") + ">" + esc(snapshotLabel(snapshots[i], i)) + "</option>";
        });
        sel.innerHTML = html;
    }

    function renderComparePickers() {
        var selA = $("eidscaCompareA"), selB = $("eidscaCompareB");
        var idxs = detailedSnapshotIdxs();
        if (idxs.length < 2) {
            // Fewer than two detailed snapshots: keep the pickers empty instead of showing a
            // phantom selection while the body says "Choose two different snapshots".
            selA.innerHTML = "";
            selB.innerHTML = "";
            eidscaState.compareAIdx = -1;
            eidscaState.compareBIdx = -1;
            return;
        }
        var html = "";
        idxs.forEach(function (i) {
            html += '<option value="' + i + '">' + esc(snapshotLabel(snapshots[i], i)) + "</option>";
        });
        selA.innerHTML = html;
        selB.innerHTML = html;
        if (idxs.indexOf(eidscaState.compareAIdx) === -1) eidscaState.compareAIdx = idxs[0];
        if (idxs.indexOf(eidscaState.compareBIdx) === -1) eidscaState.compareBIdx = idxs[idxs.length - 1];
        selA.value = String(eidscaState.compareAIdx);
        selB.value = String(eidscaState.compareBIdx);
    }

    function setView(view) {
        eidscaState.view = view;
        document.querySelectorAll(".eidsca-view-mode").forEach(function (btn) {
            btn.classList.toggle("on", btn.getAttribute("data-view") === view);
        });
        $("eidscaSnapshotFilter").classList.toggle("hidden", view !== "checks");
        $("eidscaCompareFilterA").classList.toggle("hidden", view !== "compare");
        $("eidscaCompareFilterB").classList.toggle("hidden", view !== "compare");
        $("eidscaDashboard").classList.toggle("hidden", view !== "checks");
        $("eidscaChecksView").classList.toggle("hidden", view !== "checks");
        $("eidscaTrendView").classList.toggle("hidden", view !== "trend");
        $("eidscaCompareView").classList.toggle("hidden", view !== "compare");
        if (view === "trend") renderTrendView();
        if (view === "compare") renderCompareView();
    }

    function onReady(fn) {
        if (document.readyState !== "loading") fn();
        else document.addEventListener("DOMContentLoaded", fn);
    }

    onReady(function () {
        var navToggle = $("navToggle");
        var nav = $("nav");
        if (navToggle && nav) {
            navToggle.addEventListener("click", function () { nav.classList.toggle("open"); });
        }

        if (!DATA || !snapshots.length) return; // empty state stays visible

        $("eidscaEmptyState").classList.add("hidden");
        $("eidscaContent").classList.remove("hidden");

        var detailIdxs = detailedSnapshotIdxs();
        if (detailIdxs.length) eidscaState.snapshotIdx = detailIdxs[detailIdxs.length - 1];

        renderSnapshotPicker();
        renderComparePickers();
        renderChecksView();

        $("eidscaSnapshot").addEventListener("change", function () {
            eidscaState.snapshotIdx = Number(this.value);
            renderChecksView();
        });
        $("eidscaCompareA").addEventListener("change", function () { eidscaState.compareAIdx = Number(this.value); renderCompareView(); });
        $("eidscaCompareB").addEventListener("change", function () { eidscaState.compareBIdx = Number(this.value); renderCompareView(); });

        $("eidscaResetFilters").addEventListener("click", function () {
            eidscaState.statusFilter = "";
            eidscaState.severityFilter = "";
            renderChecksView();
        });
        $("eidscaExportFiltered").addEventListener("click", function () {
            var snapshot = eidscaState.snapshotIdx >= 0 ? snapshots[eidscaState.snapshotIdx] : null;
            if (!snapshot) return; // no detailed snapshot selected - nothing to export
            var rows = [];
            evaluateSnapshot(snapshot).areaResults.forEach(function (area) {
                area.resourceBlocks.forEach(function (block) {
                    (block.controlResults || []).forEach(function (result) {
                        if (eidscaState.statusFilter && result.status !== eidscaState.statusFilter) return;
                        if (eidscaState.severityFilter && (result.control.severity || "Unspecified") !== eidscaState.severityFilter) return;
                        rows.push({ snapshot: snapshotLabel(snapshot, eidscaState.snapshotIdx), area: area.area.controlName, checkId: result.control.checkId, finding: result.control.displayName || result.control.name, status: result.status, severity: result.control.severity || "", currentValue: result.curVal, recommendedValue: result.control.recommendedValue || "" });
                    });
                });
            });
            EntraOpsReportUtils.exportRows("entraops-eidsca-findings-filtered", rows);
        });

        document.querySelectorAll(".eidsca-view-mode").forEach(function (btn) {
            btn.addEventListener("click", function () { setView(btn.getAttribute("data-view")); });
        });
    });
})();
